name: Deploy Static Build to Nginx

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Adjust as needed

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
      
      - name: Clean target folder
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "🧹 Cleaning old static files..."
            sudo rm -rf /var/www/amcm/*


      - name: Deploy dist folder via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/amcm/"
